//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fixedhitbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs_pt_BR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fixedhitbox.Resources.Langs.pt-BR", typeof(Langs_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você já tem o seu perfil da AREDL vinculada à sua conta do Discord..
        /// </summary>
        internal static string Aredl_AlreadyLinked_Description {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link para a página do seu perfil.
        /// </summary>
        internal static string Aredl_AlreadyLinked_Field_UserProfile {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Field_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Seu perfil já está vinculado..
        /// </summary>
        internal static string Aredl_AlreadyLinked_ShortMessage {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_ShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Perfil já vinculado..
        /// </summary>
        internal static string Aredl_AlreadyLinked_Title {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 | Conectando à API da AREDL....
        /// </summary>
        internal static string Aredl_ConnectingApi {
            get {
                return ResourceManager.GetString("Aredl_ConnectingApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ⚠️ | **Houve um problema de conexão!**
        ///O sistema da AREDL parece estar offline ou demorou demais para responder.
        ///*Por favor, tente novamente em alguns minutos.*
        ///        .
        /// </summary>
        internal static string Aredl_ConnectionError {
            get {
                return ResourceManager.GetString("Aredl_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot do Essencia • Integração com a AREDL.
        /// </summary>
        internal static string Aredl_Embeds_Footer {
            get {
                return ResourceManager.GetString("Aredl_Embeds_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ℹ️ | Este pedido não pode mais ser cancelado, porque o vínculo já foi confirmado.
        ///            ⛓️‍💥 | Dica: digite &quot;/unlink&quot; se realmente deseja fazer isso.
        ///        .
        /// </summary>
        internal static string Aredl_Interaction_CancelLink_AlreadyLinked {
            get {
                return ResourceManager.GetString("Aredl_Interaction_CancelLink_AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ | **Vínculo cancelado.** Nenhuma alteração foi feita..
        /// </summary>
        internal static string Aredl_Interaction_CancelLink_Success {
            get {
                return ResourceManager.GetString("Aredl_Interaction_CancelLink_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Seu perfil já estava vinculado..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_AlreadyLinked {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛ | O pedido de vínculo expirou. Execute o comando novamente..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_CacheExpired {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ✅ | **Vínculo confirmado!** Agora sua conta AREDL está conectada ao seu Discord.
        ///+ Dica: digite &quot;/records&quot; para ver seus recordes!
        ///        .
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_Success {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ | Não foi possível confirmar o vínculo..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_UnexpectedError {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você precisa ter uma conta na AREDL (All Rated Extreme Demon List) para fazer o vínculo..
        /// </summary>
        internal static string Aredl_NotFound_Description {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to website da AREDL.
        /// </summary>
        internal static string Aredl_NotFound_Field_AredlLink {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Field_AredlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 | Parece que você não tem uma conta na AREDL..
        /// </summary>
        internal static string Aredl_NotFound_Title {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ⚠️ | O perfil foi encontrado, mas os dados vieram inválidos.
        ///Pedimos que aguarde antes de tentar novamente.
        ///A AREDL deve corrigir isso logo, logo.
        ///        .
        /// </summary>
        internal static string Aredl_PendingConfirmation_When_NullApiResponse {
            get {
                return ResourceManager.GetString("Aredl_PendingConfirmation_When_NullApiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá, {0}. Nós encontramos o seu perfil!.
        /// </summary>
        internal static string Aredl_ProfileFound_Description {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Country {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogador.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Player {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordes.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Records {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não. Cancelar.
        /// </summary>
        internal static string Aredl_ProfileFound_Interaction_CancelLink {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Interaction_CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim, sou eu!.
        /// </summary>
        internal static string Aredl_ProfileFound_Interaction_ConfirmLink {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Interaction_ConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔗 | Confirmação de Vínculo.
        /// </summary>
        internal static string Aredl_ProfileFound_Title {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😓🎈 | Ocorreu um erro inesperado. Pedimos desculpas.
        ///Por favor, aguarde antes de tentar novamente.
        ///        .
        /// </summary>
        internal static string Aredl_UnexpectedError {
            get {
                return ResourceManager.GetString("Aredl_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Medindo....
        /// </summary>
        internal static string Ping_Measuring {
            get {
                return ResourceManager.GetString("Ping_Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Pong! Resposta: {0}ms..
        /// </summary>
        internal static string Ping_Pong {
            get {
                return ResourceManager.GetString("Ping_Pong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Gateway: {0:F0}ms
        ///⏱️ Resposta: {1}ms.
        ///    .
        /// </summary>
        internal static string Ping_Response {
            get {
                return ResourceManager.GetString("Ping_Response", resourceCulture);
            }
        }
    }
}
