//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fixedhitbox.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Langs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Langs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fixedhitbox.Resources.Langs", typeof(Langs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have your profile on AREDL linked to your Discord account..
        /// </summary>
        internal static string Aredl_AlreadyLinked_Description {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to your profile page.
        /// </summary>
        internal static string Aredl_AlreadyLinked_Field_UserProfile {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Field_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Your profile is already linked..
        /// </summary>
        internal static string Aredl_AlreadyLinked_ShortMessage {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_ShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Profile already linked..
        /// </summary>
        internal static string Aredl_AlreadyLinked_Title {
            get {
                return ResourceManager.GetString("Aredl_AlreadyLinked_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 | Connecting to AREDL API....
        /// </summary>
        internal static string Aredl_ConnectingApi {
            get {
                return ResourceManager.GetString("Aredl_ConnectingApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ⚠️ | **There was a connection problem!**
        ///The AREDL system appears to be offline or has taken too long to respond.
        ///*Please try again in a few minutes.*
        ///        .
        /// </summary>
        internal static string Aredl_ConnectionError {
            get {
                return ResourceManager.GetString("Aredl_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot do Essencia • AREDL Integration.
        /// </summary>
        internal static string Aredl_Embeds_Footer {
            get {
                return ResourceManager.GetString("Aredl_Embeds_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ℹ️ | This request can no longer be canceled because the link has already been confirmed.
        ///            ⛓️‍💥 | Tip: type &quot;/unlink&quot; if you really want to do this.
        ///        .
        /// </summary>
        internal static string Aredl_Interaction_CancelLink_AlreadyLinked {
            get {
                return ResourceManager.GetString("Aredl_Interaction_CancelLink_AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❌ | **Link cancelled.** No changes were made..
        /// </summary>
        internal static string Aredl_Interaction_CancelLink_Success {
            get {
                return ResourceManager.GetString("Aredl_Interaction_CancelLink_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🧲 | Your profile was already linked..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_AlreadyLinked {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_AlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌛ | The link request has expired. Please run the command again..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_CacheExpired {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_CacheExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ✅ | **Link confirmed!** Your AREDL profile is now linked to your Discord account.
        ///+ Tip: type &quot;/records&quot; to see your records!
        ///        .
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_Success {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠️ | The link could not be confirmed..
        /// </summary>
        internal static string Aredl_Interaction_ConfirmLink_UnexpectedError {
            get {
                return ResourceManager.GetString("Aredl_Interaction_ConfirmLink_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have an account on AREDL (All Rated Extreme Demon List) to make the link..
        /// </summary>
        internal static string Aredl_NotFound_Description {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AREDL website.
        /// </summary>
        internal static string Aredl_NotFound_Field_AredlLink {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Field_AredlLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💢 | It seems like you don&apos;t have an AREDL account..
        /// </summary>
        internal static string Aredl_NotFound_Title {
            get {
                return ResourceManager.GetString("Aredl_NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            ⚠️ | The profile was found, but the data was invalid.
        ///Please wait before trying again.
        ///AREDL should fix this soon.
        ///        .
        /// </summary>
        internal static string Aredl_PendingConfirmation_When_NullApiResponse {
            get {
                return ResourceManager.GetString("Aredl_PendingConfirmation_When_NullApiResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello {0}. We found your profile!.
        /// </summary>
        internal static string Aredl_ProfileFound_Description {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Country {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Player {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string Aredl_ProfileFound_Field_Records {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Field_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Cancel.
        /// </summary>
        internal static string Aredl_ProfileFound_Interaction_CancelLink {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Interaction_CancelLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes. It&apos;s me!.
        /// </summary>
        internal static string Aredl_ProfileFound_Interaction_ConfirmLink {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Interaction_ConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔗 | Link Confirmation.
        /// </summary>
        internal static string Aredl_ProfileFound_Title {
            get {
                return ResourceManager.GetString("Aredl_ProfileFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 😓🎈 | An unexpected error occurred. We apologize.
        ///Please wait before trying again.
        ///        .
        /// </summary>
        internal static string Aredl_UnexpectedError {
            get {
                return ResourceManager.GetString("Aredl_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Measuring....
        /// </summary>
        internal static string Ping_Measuring {
            get {
                return ResourceManager.GetString("Ping_Measuring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Pong! Response: {0}ms..
        /// </summary>
        internal static string Ping_Pong {
            get {
                return ResourceManager.GetString("Ping_Pong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏓 Gateway: {0:F0}ms
        ///⏱️ Response: {1}ms.
        ///        .
        /// </summary>
        internal static string Ping_Response {
            get {
                return ResourceManager.GetString("Ping_Response", resourceCulture);
            }
        }
    }
}
