// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fixedhitbox.Data;

#nullable disable

namespace fixedhitbox.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403101019_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("fixedhitbox.Models.LinkedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AredlUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("aredl_user_id");

                    b.Property<byte>("BanLevel")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ban_level");

                    b.Property<int?>("Country")
                        .HasColumnType("INTEGER")
                        .HasColumnName("country");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("discord_id");

                    b.Property<string>("GlobalName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("global_name");

                    b.Property<DateTime>("LastUpdateAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_update_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("LinkedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("LinkedUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
